[package]
name = "mkwasm"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
incremental = false
lto = true

[dependencies]
blit = { path = "../blit" }
kbd = { path = "../kbd" }
trace = { path = "../trace" }
